command/certificate/create.go

As a first time user, it's nice when the examples in the docs are cohesive. For example, I wanted to try out a general flow of (1) create self-signed root, (2) issue intermediate, and (3) issue leaf.
With consistent file names (root-ca.crt for root, intermediate-ca.crt for intermediate), the examples flow together a little better, which makes testing out this flow much simpler on the user. I also changed the ordering a little bit.

command/certificate: Make file names in docs more consistent

---

README.md
command/oauth/cmd.go
usage/css.go
usage/html.go
usage/printer.go

This adds some styles to the OAuth HTML pages:
And imports smallstep.com styles for the HTML docs:
And adds links to documentation in the README.
I'd love a one-over to make sure I haven't done something unpleasant in the Go code. It does add two fairly long lines of in-line CSS to command/oauth/cmd.go

HTML Styles

---

Makefile
debian/changelog
debian/control
debian/rules
debian/step-cli.bash-completion
debian/step-cli.postinst
debian/step-cli.prerm
debian/step.bash-completion

This PR Fixes #26 and renames the step debian package as step-cli

Rename debian package to step-cli

---

.gitignore
command/crypto/jwk/create.go
jose/generate.go
jose/generate_test.go

Opening this to start a bit of conversation on `x5c` support with JWKs (`step crypto jwk create`).
First, I think that re-using `--from-pem` is the right way to go, as opposed to creating a `--from-certificate` flag. Certificates behave much like public keys, with the added benefit that the key is signed and attested by some authority. Since the `--from-pem` flag already supports pubkeys, adding certificate support here makes some sense.
This PR refactors some of the code in `jose/generate.go` and adds a switch case to allow for a JWK to be generated from a `*x509.Certificate` type.
Usage:
```
$ step crypto jwk create foo-jwks.json nopriv --from-pem path/to/foo-bundle.crt
```
Output:
```
$ cat foo-jwks.json 
{
"use": "sig",
"kty": "EC",
"kid": …
```

command/crypto/jwk/create: Add initial x5c support

---

Gopkg.lock
usage/help.go
usage/html.go
usage/printer.go
usage/report.go

Implemented a simple word/line counter report based on the HTML page generation written to the output ./html directory.
https://github.com/smallstep/ca-component/issues/79

Issue 79: Add a json reporter to quantify the extend of the cli's documenation

---

Gopkg.lock
command/crypto/otp/otp.go
integration/help_quality_test.go
usage/report.go

This PR makes it easier to continuously and quickly gauge simple quality gates such as 
* minimum word/line count per help sections, 
* headline consistency in sections across the documentation, and 
* surfacing any unresolved TODOs.
Minor improvements:
* Correction of a headline to enforce consistency.
* Removes dependency to external library to strip tags, use regex instead

Add simple quality gates to integration tests 

---

command/ca/bootstrap.go
command/ca/certificate.go
command/ca/init.go
command/ca/provisioner/getEncryptedKey.go
command/ca/root.go
command/ca/token.go
command/certificate/bundle.go
command/certificate/certificate.go
command/certificate/lint.go
command/certificate/sign.go
command/certificate/verify.go
command/crypto/change-pass.go
command/crypto/hash/hash.go
command/crypto/key/format.go
command/crypto/key/key.go
command/crypto/keypair.go
command/crypto/nacl/auth.go
command/crypto/nacl/secretbox.go
command/crypto/nacl/sign.go
command/crypto/otp/generate.go
command/crypto/otp/verify.go
command/version/version.go
usage/help.go

Unify short usage to use the 1st person. Fixes #37

Use 1st person for short usage

---

crypto/x509util/crt.go

* document acceptable input
* don't fail if input is not either a file or directory
* trim space in comma delineated file list

fix ReadCertPool function

---

command/ca/certificate.go
command/ca/token.go
command/certificate/create.go
flags/flags.go

Add support for --not-before and --not-after flags in `step certificate create`. Fixes #51

Allow to add custom validity in `step certificate create`

---

crypto/x509util/intermediateProfile.go
crypto/x509util/leafProfile.go
crypto/x509util/rootProfile.go

* root and intermediate certs only require the CertSign key usage.
do not need key encipherment or digital signature by default.
* intermediate certificate should not have client/server auth extended
key usage.

Audit of default key usage for root and intermediate certs

---

Gopkg.lock
Gopkg.toml
command/ca/ca.go
command/ca/federation.go
crypto/pki/pki.go

This PR adds two new commands to download the roots bundle and the federated bundle from the CA.
* `step ca roots`
* `step ca federation`
Both require the initial root to be present or passed using a flag.
Fixes smallstep/certificates#19
Note: before merging we will need to update the dependencies pointing to master.

Add support for multiple roots and federation

---

command/certificate/inspect.go

Add support for inspecting DER certificates or certificate signing requests. Only leaf certificates are supported on DER form.
Fixes #54

Add support for inspecting DER certificates

---

command/certificate/certificate.go
command/certificate/key.go
crypto/keys/key.go
crypto/keys/key_test.go
crypto/pemutil/pem.go
crypto/pemutil/pem_test.go
jose/parse.go

This PR allows using certificates as keys in commands like `step crypto jwt verify --key cert.crt ...` and adds a command to extract public keys from certificates or CSRs `step certificate key cert.crt`
Fixes #67, #68, and #69

Allow to use certificates as keys and add command to extract public keys

---

ui/ui.go

Homebrew tests on travis fails trying to allocate a terminal. This fix returns the default value if set before allocating a terminal.
Fixes #75

Fix homebrew tests that fails trying to allocate a terminal.

---

command/certificate/create.go

```$ step certificate create --csr hello.smallstep.com hello.csr hello.key
Please enter the password to encrypt the private key:
Your certificate signing request has been saved in hello.csr.
Your private key has been saved in hello.key.
$ step ca sign hello.csr hello.crt
✔ Key ID: jO37dtDbku-Qnabs5VR0Yw6YFFv9weA18dp3htvdEjs (mariano@smallstep.com)
✔ Please enter the password to decrypt the provisioner key:
✔ CA: https://ca.smallstep.com:9000/1.0/sign
Unauthorized
```
Google Chrome version 58, released in April 2017, removed support for the X.509 certificate Subject Common Name (CN) as a source of naming information when validating certificates. As a result, certificates that do not carry all relevant domain names in the Subject Alternative Name (SAN) extension result in validation …

step certificate create: Added subject as SAN if empty

---

command/ca/certificate.go
command/ca/offline.go
command/ca/token.go

This PR forces the use of default token validity when `step ca certificate` and `step ca sign` are used without the `--token` flag. The token validity is irrelevant as the token is used immediately.
Fixes #97

Use default token duration in step ca certificate / sign

---

Gopkg.lock
Gopkg.toml
command/ca/certificate.go

This PR adapts the CLI to work with the certificates TimeDuration type. Now the `/sign` endpoint accepts durations and RFC3339 timestamps.
Fixes #60
Depends on smallstep/certificates#56

Use TimeDuration for step ca certificate and sign

---

Gopkg.lock
Gopkg.toml
command/ca/init.go
command/certificate/create.go
command/certificate/fingerprint.go
command/certificate/sign.go
command/certificate/verify.go
command/oauth/cmd.go
crypto/pki/pki.go
crypto/x509util/convert.go
crypto/x509util/convert_test.go
crypto/x509util/csr.go
crypto/x509util/csr_test.go
crypto/x509util/identity.go
crypto/x509util/intermediateProfile.go
crypto/x509util/leafProfile.go
crypto/x509util/profile.go
crypto/x509util/rootProfile.go
utils/cli.go

This PR tries to remove the use of the internal `cli/pkg/x509` as much as possible without affecting to the current functionality.
Fixes #95

Use standard x509 as much as possible

---

Makefile
make/common.mk
make/docker.mk

This PR adds the `:latest` tag to all release builds, but not the release candidates.

Add :latest tag to docker on the release builds

---

Gopkg.lock
Gopkg.toml
command/crypto/jwt/sign.go
jose/types.go

This PR adapts certificates code to go-jose@2.3.0, claims `iat`, `nbf`, and `exp` are now pointers instead of values. This PR won't be merged until square/go-jose#224 gets merged.
With square/go-jose#224 merged, Ed25519 JWK keys will be properly marshaled. Instead of waiting for the merge, we are using our fork.
Fixes #105

Update go-jose to 2.3.0.

---

cmd/step/main.go
command/ca/revoke.go
command/crypto/jwk/create.go
command/crypto/jws/sign.go
config/config.go
usage/renderer.go

This PR allows the re-use the config and version command in multiple tools. It also includes a change in the terminal help renderer that helps with the formatting of list long definitions better, using a renderer more similar to the HTML. Long definitions were not rendered properly and it was hard to fix, now long definitions are looking good:
```
Superseded
The certificate is being replaced.
CessationOfOperation
If a CA is decommissioned, no longer to be used, the CA's certificate
should be revoked with this reason code. Do not revoke the CA's certificate if
the CA no longer issues new certificates, yet still publishes CRLs for the
currently issued certificates.
```
But short definitions are now more verbose, what it used to be:
```
HS256       HMAC using SHA-256
HS384       HMAC using …
```

Help formatting and generalizing of version

---

Gopkg.lock
Gopkg.toml
command/ca/ca.go
command/ca/certificate.go
command/ca/offline.go
command/ca/provisioner/add.go
command/ca/provisioner/remove.go
command/ca/sign.go
command/ca/token.go
exec/exec.go
token/parse.go
token/parse_test.go

This PR add support for using the new cloud provisioners in the `step ca` commands:
* GCP instance identities
* AWS instance identities
* Azure instances using OAuth tokens
Related to https://github.com/smallstep/certificates/pull/65

Cloud identities

---

cmd/step/main.go
command/base64/base64.go
command/crypto/jwt/sign.go
utils/read.go
utils/read_test.go

This PR adds a new command `step base64` to base64 encoding or decoding.
Decoding format is automatically detected, while the encoding supports the standard encoding as well as url encoding both with or without padding.

Add command for base64 encoding/decoding 

---

Gopkg.lock
Gopkg.toml
command/ca/certificate.go
command/ca/offline.go
command/ca/token.go

This PR allows using custom common names in cloud identity provisioners.
Related to https://github.com/smallstep/certificates/pull/84
It also includes a change in certinfo that adds support for extra fields in the x509 provisioner extension and some minor UI improvments. See https://github.com/smallstep/certinfo/commit/fef09aeb6b3b6451151ae248670cf020454c0d5b

Allow custom common names in cloud identity provisioners.

---

command/ssh/certificate.go

Brings `ssh certificate` subcommand's help in line with the new top-level command. Also limits description to scope of CA issuing certs and how to use them.

Help edits to limit scope to CA issuing certs and how to use them

---

Gopkg.lock
command/ca/certificate.go
command/ca/provisioner/add.go
command/ca/provisioner/remove.go
command/ca/sign.go
command/ca/token.go
command/certificate/inspect.go
command/certificate/sign.go
errs/errs.go
utils/cautils/acme_flow.go
utils/cautils/acmeutils.go
utils/cautils/offline.go
utils/cautils/token_flow.go

Integrate with any ACME 2.0 server to get certificates using standalone or webroot mode.

ACME client support for standalone and webroot mode

---

command/certificate/inspect.go
crypto/pemutil/pem.go
crypto/pemutil/pem_test.go

Certificate signing request created by some versions of java's keytool use the PEM header `NEW CERTIFICATE REQUEST`. This PR adds support for inspecting and signing these files.

Support for NEW CERTIFICATE REQUEST header

---

README.md

This is just a simple fix for the url for the debian package, the version has a `v` in front of it for the branch but not the package filename itself

Fix typo on install url for debian

---

Gopkg.lock
command/ca/renew.go
utils/cautils/certificate_flow.go
utils/cautils/offline.go

* update offline and online tokens to use the new API.
* the old API is still accessible, but it is deprecated and we'll be
looking to push all new clients to use the new API.

Update cli to use the newly added CertChainPEM in the step-ca API

---

command/oauth/cmd.go

This seems to do the trick for redirecting to a static hosted page. I have no clue how to write a test for this.. but feel free to pass along hints or merge anyway.. :man_shrugging:

Redirect to hosted sso success page after oauth flow

---

command/ca/bootstrap.go
command/oauth/cmd.go
flags/flags.go
utils/cautils/teams.go

Add a `--redirect-url` string option to the boostrap command that allows
the terminal redirect in the OAuth flow to be configured. This is useful
if you want to display a more interesting page than the locally hosted
basebones "Success" page.
If the user configures step-cli using the `ssh config` command and passes
the `--team` option, set the redirect url to:
https://smallstep.com/app/teams/sso/success
so that the flow ends on a page that instructs users on what to do next.

oauth: Add terminal redirect URL option

---

command/ssh/config.go
utils/cautils/teams.go

Allow users to specify the endpoint that `step ssh config --team` uses to
pull inital configuration. If no endpoint is specified, default to
https://api.smallstep.com/v1/teams/<name>/cas/default
If the user-specified endpoint contains any "<>" sequences, replace them
with the team name.

teams: Add --endpoint option

---

utils/cautils/teams.go

The redirect URL can now be specified in the initial config step pulls
from the --endpoint specified during `step ssh config --team`.

teams: Add redirect-url to the config payload

---

docs/local-development.md

- remove vtest description. See https://github.com/smallstep/cli/commit/71ee01bbfa698835c9bfac73458a95113181abef
- fix linter desc metalinter -> golangci-lint. See #130
I tried and found some deprecated guide descriptions as above.
Thank you.

Fix local development doc

---

command/path/path.go

Previously, the Description for “step path” command is
“step ca command prints …”, it should be “step path command prints …”.
This changes fix the typo.

command/path: fix typo on command description

---

utils/cautils/teams.go

Use https://api.smallstep.com/v1/teams/:slug/authorities/ssh.

ssh/config: Update default team URL

---

command/ssh/certificate.go
command/ssh/ssh.go
go.mod

Alternatively, allow the user to specify their own UUID. Adding an ID
derived from the machine ID allows us to authorize hosts to access their
own resources by ID. The machine-id is not supposed to be sent around as
a raw UUID. So we HMAC it with an application "secret" and use the first
sixteen bytes of the resulting sha256 sum to as the entropy source when
generating a new "random" UUIDv4.

ssh: Add machine-id hash to host certificate

---

command/ssh/certificate.go
command/ssh/ssh.go

Apparently some images don't properly handle the machine-id and it ends
up not being unique. By default play it safe and generate our own UUID.
Deriving a UUID from `/etc/machine-id` is still supported. To trigger
that behavior, pass 'machine' as the `--host-id` flag.

ssh/certificate: Generate a random UUID by default

---

autocomplete/zsh_autocomplete

Closes #240
This revision modifies the ZSH autocomplete script to check if the output of `--generate-bash-completion` is empty, and if is, it defaults to autocompleting files.
💔Thank you!

Fix autocompletion for file paths in ZSH [#240]

---

Makefile
make/common.mk

The included sub-Makefiles are present in the source code. Thus, they should be present always. There is no need to silently fail if the files are not found. In contrary this indicates a clearly broken setup.

Improvements in Makefile

---

Makefile
make/bundle.sh

Partially solves: smallstep/certificates#152
This revision:
- Adds rules for building ARM Linux releases for Arm64 and ArmV7 (tested on my RPI)
- Refactors out the BUNDLE script from Makefile into a shell script
- improves readability
- adds support for specifying architecture and artifact directory separately from each other
Thank you!

Add ARM support for step-cli

---

command/ssh/ssh.go

Just a small clarification in the documentation for `step ssh certificate`.

Clarify principals flag for SSH certificates

---

command/ssh/fingerprint.go

Wrote a Usage summary for `step ssh fingerprint`. The old one was the same text as `step ssh list`.

Usage summary for `step ssh fingerprint`

---

command/ssh/revoke.go

The ssh-revoke documentation is explaining how to use ssh-renew. This should line up the documentation of ```step ssh help revoke``` to align with the actual usage.

Fixed ssh revoke help documentation to reflect actual revoke usage.

---

command/ssh/hosts.go

When hostnames run up against the full length of their column there will be no separation between hostname and ID columns. This change will fix this. Please see before after example below.
:-(
```
HOSTNAME                                        ID                                      TAGS
ec2-18-xxx-x-x.compute-1.amazonaws.com          b160dd85-3ead-4479-xxxx-762d773dcce0    stage=dev
ec2-52-xx-xxx-xx.us-west-1.compute.amazonaws.combe5078ad-2c67-46ee-xxxx-7f658e83ca5a    stage=dev,box=small
ip-172-31-72-13                                 698d7af5-3f48-4477-xxxx-677fcf2fc158    stage=dev
```
:-)
```
ec2-18-xxx-x-x.compute-1.amazonaws.com                  b160dd85-3ead-4479-xxxx-762d773dcce0    stage=dev
ec2-52-xx-xxx-xx.us-west-1.compute.amazonaws.com …
```

Cosmetic improvement: avoid unintentional concat of columns

---

command/path/path.go

Just a minor edit to add a tip about `STEPPATH` when running `step path --help`

Add tip about STEPPATH to step path docs.

---

command/certificate/create.go

Forcing this for root CA and intermediate CA certs was resulting
in the subject (typically a company name) being interpreted as
a dnsName SAN.  This produced an invalid certificate.  It is also
highly unusual to have a root CA with a SAN at all as seen in
censys so it's best to leave it out.
Fixes #263

certificates: create: only force default SAN for leaf certs

---

command/ssh/certificate.go
command/ssh/login.go

This PR avoids a panic when the add user certificate is not provided.
On OIDC provisioner the certificate has two identities and
step-certificates does not create a user provisioner certificate.
This change avoid the panic and displays a proper message.
A fix in certificates is required to allow user provisioner
certificates with OIDC provisioners.
Partialy fixes #268

Avoids panic when the add user certificate is not provided.

---

command/certificate/create.go

Uppercase `s` in TLs at `command/certificate/create/go:182`.

Fix typo: TLs => TLS

---

command/oauth/cmd.go

Some IdPs do not support the recommended 127.0.0.1, and only support
localhost as redirect uri. This change allows to run use localhost
with `step oauth --listen localhost:0`.
Fixes #169
This is an alternative approach to #278 that integrates better with step-ca

Redirect to localhost using the `--listen` flag

---

command/crypto/nacl/box.go
command/crypto/nacl/nacl.go
command/crypto/nacl/secretbox.go

In nacl box and secretbox operations is hard to use a binary nonce. This change provides the posibility to encode the nonce in base64 if the `base64:` prefix is used.
Fixes #279

Add support for base64 encoded nonces.

---

command/crypto/nacl/box.go
command/crypto/nacl/nacl.go
command/crypto/nacl/secretbox.go

This PR adds the `string:` prefix after Mike's suggestion in https://github.com/smallstep/cli/issues/279#issuecomment-624881170

Add support for the string: prefix

---

command/certificate/fingerprint.go
command/certificate/inspect.go
command/certificate/lint.go
command/certificate/remote.go
command/certificate/remote_test.go
command/certificate/verify.go

Added the ability use TLS Server Name Indication (SNI) to specify
which certificate the server should send. This can be useful when
the server supports multiple certificates or when the DNS doesn't
match the IP address (e.g. in development scenarios) but we still
want certificate validation to be performed.
This option was added to all commands that support a remote fetch
of a peer certificate. These commands include:
- `fingerprint`
- `inspect`
- `lint`
- `verify`
Fixes #295

add support for TLS Server Name Indication

---

command/crypto/key/format.go

This PR allows to use STDIN in step crypto key format, this way concatenating commands is easier.
For example, to get the public key in ssh format from a private key, we can use:
```
step crypto key public private.key | step crypto key format --ssh
```

Allow to use stdin in step crypto key format.

---

command/certificate/inspect.go
command/certificate/inspect_test.go

Add the `--format pem` option to `step certificate inspect`. This formatting option allows the certificate (and certificate chain when using `--bundle`) to be printed in PEM format.
Example Use:
```
$ step certificate inspect --format pem https://smallstep.com
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
Fixes #214

Add -format pem option to step certificate inspect

---

docker/Dockerfile

This PR allows to create step-cli containers using custom uid and gid for the step user using docker build's `--build-arg` flags.

Make step uid and gid configurable with docker arguments

---

command/ssh/list.go

Fix a simple typo in the `subject` positional argument on the usage page of `step ssh list`

Fix typo in ssh list command usage

---

crypto/sshutil/inspect.go
crypto/sshutil/sshutil.go

I've added support for the new `-sk` key types in `step ssh inspect`. Also was able to refactor the inspection code. Between `crypto/sshutil/inspect.go` and `crypto/sshutil/sshutil.go` there were two ways of determining public key type, size, and fingerprint. Now there's just one.
Here's a cert signed by an SK-ECDSA key to test with:
````
ssh-rsa-cert-v01@openssh.com AAAAHHNzaC1yc2EtY2VydC12MDFAb3BlbnNzaC5jb20AAAAgNydgSUva3aquOZKH1YPLmUUsdSfNGT3ip5z3G+U2urYAAAADAQABAAABAQDIQqOkTPD8L2xGTHhv8hrUm8qIvz9eoI2oq72s4hGlcPIPp6kEegma0wV8gAzjd3zT39V9bzwyN471tjG+45yNF1NbJiNQ72rLPwLz0FZ5zJfULZ6coqNYDF30B7URs/pGATHeU/ChcszrD33v2HWAbP1C/YzCLjarqk2NRFJOSLcee88pQeOWaCQhkazFMQG3a8N5nw31S9L5CkIUxp0XavsQONSk1WEbifDOekoheVc0+nfYX7nluZlm0zILsKm6107+rva9gwRWZvF1eRH6omTTF76CNsTT9Ed7HcdlDB+1ItXZiLycXMJ5Uga1dAtGEC …
```

Support -sk key types in ssh inspect; refactor inspection code

---

command/certificate/remote.go
crypto/x509util/leafProfile.go
crypto/x509util/profile.go
crypto/x509util/profile_test.go

This PR disables key encipherment for leaf certificates without RSA keys.
See:
https://github.com/golang/go/issues/36499
https://tools.ietf.org/html/draft-ietf-lamps-5480-ku-clarifications-02

Key encipherment

---

command/oauth/cmd.go

Trim trailing newlines from verification code using "--console"

---

crypto/x509util/crt.go
crypto/x509util/crt_test.go

This PR changes x509util.SplitSANs to detect properly URIs like `mailto:jane@doe.com` as a URI instead of an email.

Detect properly URIs with @

---

command/crypto/key/fingerprint.go
command/crypto/key/key.go

This PR includes a command that prints the fingerprint of a public key. It supports also printing the fingerprint of the public key embedded in certificates, certificate requests, as well as the one in a private key.

Add step crypto key fingerprint command.

---

make/docker.mk

This is a parallel update of the Docker makefile to support `buildx` on Darwin, from https://github.com/smallstep/certificates/pull/346

Get docker buildx working on both darwin & linux

---

README.md
command/crypto/nacl/sign.go
docs/CONTRIBUTING.md
usage/usage.go

For simplicity we only have Discussions enabled on smallstep/certificates, so I'm linking to that.

Migrate to GH Discussions tab

---

command/ssh/certificate.go
command/ssh/login.go
command/ssh/proxycommand.go
command/ssh/ssh.go
go.sum

For user certificates, if an email is passed as a principal, we will include in the principals list the email, and the local-part. This imitates the behavior for OIDC provisioners on other provisioners like JWK.
On `step ssh certificate` we will only include them if no principals are passed using the `--principal` flag.
Fixes #389

Add local part of an email and email as a principals.

---

command/ssh/login.go
command/ssh/logout.go
flags/flags.go

This change adds the flags --identity=value to `step ssh login` and `step ssh logout` so we don't need to pass an extra argument if the identity is set in defaults.json or as an environment variable.
Fixes #369

Allow to configure the identity argument in defaults.json

---

command/certificate/certificate.go
command/certificate/p12.go
go.mod
go.sum

This PR adds a `step certificate p12` subcommand to support bundling keys and certificates together into PKCS12 / p12 / pfx files, as discussed in #244 
These are commonly used for installing client certificates into Firefox / Windows, and for configuring server certificates for Java applications.
The arguments / options are an attempt at being easy to use, without forcing the user to understand all the different types of p12 that exist.
A password is specifiable on the CLI as one is required for .p12, but is a bit pointless as the encryption is weak. The author of the upstream library this PR uses suggests using a nominal password then protecting the result file using a stronger external method:
https://github.com/SSLMate/go-pkcs12/blob/master/pkcs12.go#L33

Add a `p12` command to create PKCS12 store files

---

cmd/step/main.go
command/ca/init.go
go.mod
go.sum

This PR adds support for CloudCAS in step ca init.
Now it's possible to start the ca.json configuration running `step ca init --ra cloudCAS`. The intermediate resource can be passed with the flag `--issuer` and the optional credentials file with `--credentials-file`.
Requires https://github.com/smallstep/certificates/pull/402

Add support for cloud CAS in step ca init.

---

command/ca/ca.go
command/ca/certificate.go
command/ca/sign.go
command/ca/token.go
make/common.mk
utils/cautils/token_flow.go
utils/cautils/token_generator.go

This PR adds support for `--provisioner-password-flag` in `step ca sign`. It also adds that alias to `step ca token`.
Note that I also removed `--password-file` in `step ca certificate`; it was there just because it was a hack to allow its use. I didn't add it as an alias if we want to reuse it for encrypting the generated key.
Fixes #378

Provisioner password flags

---

README.md

Url went to oauth instead of ssh.

Fixes step ssh documentation url in README.md

---

command/oauth/cmd.go
exec/exec.go

Allow users to specify which browser is used for OAuth flows. This is only implemented for macOS for now. The tool we're using on Linux (`xdg-open`) doesn't seem to have any simple way to set which browser is used (it always uses your system's default browser). It may be possible to extend this to Windows, but I haven't looked yet. For now I've made this a hidden option since it seems pretty niche and it's not documented, etc.
To configure which browser is used you can pass the `--browser /Path/To/Browser.app` flag into `step oauth`. For other subcommands that depend on `step oauth`, like `step ssh proxycommand` and `step ca certificate`, you can set the `STEP_BROWSER=/Path/To/Browser.app` environment variable or set `"browser": "/Path/To/Browser.app"` in your `defaults.json` (which is …

Allow configuration of browser used for OAuth on macOS.

---

command/fileserver/fileserver.go

This PR adds support for requiring client certificates in the test tool `step fileserver`
Fixes #320

Add support for mtls in `step fileserver`.

---

.github/workflows/release.yml
.github/workflows/test.yml
command/certificate/p12.go

This PR adds the flags `--no-password --insecure` to `step certificate p12` to encrypt a PKCS#12 archive with a blank password.
Fixes #414

Add no-password to step certificate p12

---

command/certificate/create.go

This PR change the `ioutil.ReadFile` for `utils.ReadPasswordFromFile`. This function trims spaces and new lines at the end of the file.
Fixes #428

Fix read password in step certificate create

---

.goreleaser.yml
Makefile
docs/CONTRIBUTING.md

this allows e.g. some routers to make use of `step cli`
hey there! huge fan of step and y'all's drive to make this ecosystem better :)
this is a small change that just adds a `linux/mips` build target. the binary size that golang produces isn't ideal for some devices, but `step` is worth it :) there may be some easy wins there for the future, although i haven't done any homework there.

add linux/mips build target

---

make/bundle.sh

This adds the autocomplete directory to tar.gz archives which is already included in Debian step-cli packages.
💔Thank you!

Include autocomplete in distribution archives.

---

command/crypto/key/fingerprint.go
command/crypto/key/format.go
command/crypto/key/inspect.go

The following commands now support keys in JWK format.
```
step crypto key fingerprint
step crypto key format
step crypto key inspect
```

Add support for JSON Web Keys in step crypto key commands

---

command/ca/renew.go
command/ca/revoke.go
command/ca/root.go

This PR changes all the custom transports being used to add `Proxy: http.ProxyFromEnvironment`
Related to smallstep/certificates#535
Full fix requires smallstep/certificates#540

Always specify a Proxy in all custom transports.

---

Makefile

- Even when in CI e.g. github-action or travis
Fixes broken version in Homebrew. They're also using github actions so, `GITHUB_REF` is set and overrides our environment given VERSION variable.

In Makefile always use the VERSION from ENV if not empty.

---

command/certificate/verify.go

This change allows to validate any type of cert, no matter the extended key usage of it. Previously only certs with server auth were considered valid.
In the future we should add some kind of 'purpose' flag and configure the verify options accordingly.
Related to #467

Allow verification of any type of certs.

---

.gitignore
command/ssh/inspect.go

Useful for implementing customizing `AuthorizedPrincipalsCommand`, e.g. for smallstep/certificate#547

Add json output to step ssh inspect

---

command/ssh/login.go
command/ssh/proxycommand.go
command/ssh/ssh.go

~~OIDC provisioners use an identity function to get the principals for a given email, so there's no need to provide principals.
Moreover, if the email and principal does not match `step ssh proxycommand` will fail if the username does not match the email address.~~
~~For an unknown reason this feature was removed in an unrelated commit smallstep/cli@2c9b200~~
This PR clarifies some comments about the use of the email as a subject in OIDC provisioners and appends to the list of principals the requested one if different being case sensitive.
Fixes: smallstep/certificates#550

Clarify comments and add requested principal

---

command/crypto/jwt/sign.go

Some CI platforms will feed us an empty pipe as STDIN (i.e. GitHub Actions). This means that the following command — which would work fine locally — will fail on the CI:
```
$ step crypto jwt sign --key key.pem --subtle
error decoding JSON from STDIN: EOF
```
This PR ensures that if no payload is specified and STDIN is empty, we treat it as a valid empty JSON. This is consistent with the current behaviour when STDIN is not a pipe.

Make empty STDIN work for `crypto jwt sign` when no input is specified

---

flags/flags.go

This PR changes the usage of the --redirect-url. This flag is used in the `step oauth` command and can also be used in the `step ca bootstrap` command to write it in the defaults.json file.
This flag won't have any effect on oob flows, but we cannot fail if both are used because it will cause errors on specific configurations where errors are not expected.
Fixes #510

Clarify the use of the --redirect-url flag

---

command/ssh/needsRenewal.go
command/ssh/ssh.go

This PR adds the `ssh needs-renewal` command based off of the `certificate needs-renewal` command.
It addresses a similar issue to https://github.com/smallstep/cli/issues/398 but for SSH host certificates.

Add `ssh needs-renewal` command

---

command/ca/ca.go
command/ca/rekey.go
command/ca/renew.go
utils/cautils/client.go
utils/cautils/offline.go

Closes #316 by adding `step ca rekey` as a command. 
Example Uses:
Rekey the certificate and write the certificate and newly generated private key to specified files:
`step ca rekey internal.crt internal.key --out-crt foo.crt --out-key foo.key
`
Rekey the certificate using a given private key:
`step ca rekey internal.crt internal.key --private-key foo.key`
--offline flag added on also works

Step ca rekey Command

---

crypto/pemutil/pem_test.go
crypto/x509util/identity_test.go

After this change `make test` passes again.

Update tests to match current exception strings for malformed certs.

---

CHANGELOG.md
make/common.mk

Fixes #535
To get the Go path, make/common.mk used `$(go env GOPATH)` which was thus evaluated by Make (wrongly, to an empty string). To get it evaluated (properly) by the shell, the expression must be `$$(go env GOPATH)`.
This PR adds the missing `$`.

Fix `make bootstrap` failing to install `golangci-lint` using GOPATH

---

CHANGELOG.md

U.S. date format generates confusion around the world, please use ISO-8601 dates

CHANGELOG: use ISO-8601 dates

---

CHANGELOG.md
command/ca/init.go
ui/options.go

Change dns to string slice in `ca init` but backwards compatible csv

---

CHANGELOG.md
command/ca/certificate.go
command/ca/sign.go
utils/cautils/certificate_flow.go

This PR removes the checks in `step` when certificates are signed using OIDC provisioners.
With OIDC tokens the CSR will be built based on the `--san` flags, subject argument, token.sub, token.email and token.iss based on the following rules:
* If at least one `--san` is provided: CN=subject SANs=splitSANs(sans)
* If no sans and subject == token.email: CN=token.sub SANs=token.email, token.iss#token.sub
* if no sans and subject != token.email: CN=subject SANs=splitSANs(subject)
Fixes #340
Notes: 
* If a non-admin uses a subject that does not match his email the CSR sent to the CA will be build using the rules above, but he will get a certificate with CN=token.sub, SANs=email, token.iss#token.sub
* Extra checks that we want to add in the CA are not part of the scope of this PR, and we …

Remove checks for OIDC provided certificates.

---

CHANGELOG.md
command/oauth/cmd.go
command/ssh/config.go
utils/cautils/token_generator.go

This PR allows to use `--set` and `--team` together in the `step ssh config`. There's no need to make them incompatible and can be useful for some templates.
This PR also allows overriding a fixed listen-address coming from the CA with the value on an environment variable. This combined with a new `--listen-url` flag allows to do the OAuth flow in restricted environments like containers if the IDP doesn't support the out of band flow.
These changes allow the following flow with an OIDC provisioner:
```
$ docker run -it -p 10000:10000 smallstep/step-cli:latest /bin/bash
bash-5.1$ step ca bootstrap --ca-url ...  --fingerprint ...
bash-5.1$ export STEP_LISTEN=0.0.0.0:10000
bash-5.1$ export STEP_LISTEN_URL=http://127.0.0.1:10000
bash-5.1$ step ca certificate mariano@smallstep.com mariano.crt …
```

Flexible config and OAuth redirect_uri

---

autocomplete/bash_autocomplete
autocomplete/zsh_autocomplete

The [bash] and [zsh] autocomplete scripts from upstream [urfave/cli] now handle autocompletion of files and also correctly handle command flags.
[bash]: https://github.com/urfave/cli/blob/master/autocomplete/bash_autocomplete
[zsh]: https://github.com/urfave/cli/blob/master/autocomplete/zsh_autocomplete
[urfave/cli]: https://github.com/urfave/cli

Update autocomplete scripts from urfave/cli

---

CHANGELOG.md
go.mod
go.sum

Add FreeBSD support to `step certificate install`.
I've tested `step` with the user-provider implementation of truststore with PRs https://github.com/smallstep/truststore/pull/7 and https://github.com/smallstep/truststore/pull/9 and it worked on FreeBSD13.

Upgrade trustore.

---

command/ca/init.go

Add clarification for the listen port in `step ca init --helm`
Fixes smallstep/helm-charts#82

Clarify listen port message in `step ca init --helm`

---

command/ca/provisioner/add.go

- oidc uses only the clientID as the unique identifier.

Update OIDC add error for duplicate ID

---

utils/cautils/offline.go

When templates are used in offline mode, the `TemplateData` was missing in X.509 signing requests, SSH signing was working fine.
Fixes #624

Pass missing template data in X509 sign offline mode

---

utils/cautils/acmeutils.go

When performing an ACME flow with an existing CSR, not all SANs would be in the ACME order. This PR fixes that.
It's related to https://github.com/smallstep/certificates/discussions/819.

Add IPs as SANs when performing ACME flow with existing CSR

---

.goreleaser.yml
autocomplete/README.md
cmd/step/main.go
command/completion/completion.go
debian/step-cli.bash-completion
make/bundle.sh
scripts/postinstall.sh

Fixes #622
Add shell completion command. #622
I removed the `-o nospace` from `autocomplete/bash_autocomplete`. I think it's far better.

Add completion command

---

command/ssh/proxycommand.go

This PR adds the --provisioner-password-file flag to `step ssh proxycommand`
Machines doing ssh client connections might want to use a JWK provisioner to create the SSH certificate, this change allows to automatically create the token if `--provisioner` and `--provisioner-password-file` are passed.

Add the --provisioner-password-file to proxycommand.

---

.gitignore

This PR includes `.envrc` to `.gitignore` as a convenience to engineers who work on `cli` while at the same time use a tool like [`direnv`](https://direnv.net/).

git: ignore .envrc files

---

.github/workflows/release.yml
.github/workflows/test.yml
CHANGELOG.md
command/certificate/remote_test.go

This PR changes the supported versions of Go to 1.17 and 1.18, using Go 1.18 for releases.

Go 1.18 support 

---

.github/workflows/test.yml
make/common.mk

Upgrade golangci-lint to v1.45.2 so it works with Go 1.18.

golangci-lint v1.45.2 avoids panic on Go 1.18

---

command/certificate/fingerprint.go
crypto/x509util/crt.go
crypto/x509util/crt_test.go

Add optional SHA1 fingerprint output for certificates has requested in https://github.com/smallstep/cli/issues/611

Add optional SHA1 fingerprint output for certificates

---

command/context/list.go
go.mod
go.sum

Sort context list alphabetically
Hard to find contexts when there's no order
I made it default to sorting alphabetically (case-insensitive), because I think that makes sense for most, if not all, use cases.

Sort context list alphabetically

---

command/ca/certificate.go
command/ca/sign.go

`--password-file` flag for offline mode
Allows use of `offline` mode without any additional command line input. Useful for scripting.
It's fairly niche, and I don't think we need any additional documentation.
All
Fixes https://github.com/smallstep/cli/pull/673

Add --password-file flag for offline mode without password input

---

command/crypto/keypair.go

An empty password doesn't make sense, certainly not given there's the `--no-password` option. This commit adds the empty validation check to the password prompt, always requiring a password to be provided by the user. 
An alternative would be to generate a password if the value is empty. Both methods are currently used in the CLI. The ones that generate a password are mostly used for `ca` commands. That's why I chose to validate the value to not be empty instead of generating one, as `crypto keypair` has nothing to do with the CA directly.

Check input password value to not be empty on keypair creation

---

command/ssh/inspect.go
crypto/sshutil/inspect.go

This PR adds the signature and signature type to the `step ssh inspect` command. Fixes #699
Now a certificate will inspect as:
```console
$ step ssh inspect mariano-cert.pub
mariano-cert.pub:
Type: ecdsa-sha2-nistp256-cert-v01@openssh.com user certificate
Public key: ECDSA-CERT SHA256:a8SHPBTzbkmcfAp+FWBoOj87k7wnGEG3qleXFPXz8FM
Signing CA: ECDSA SHA256:ExpOxCvxwkeqnHuUtTR5dhsTUFgcN1QeuAYqOGE6200 (using ecdsa-sha2-nistp256)
Key ID: "mariano@smallstep.com"
Serial: 6770237405177342977
Valid: from 2022-02-01T12:01:07 to 2022-02-02T04:02:07
Principals:
mariano@smallstep.com
Critical Options: (none)
Extensions:
permit-port-forwarding
permit-pty
permit-user-rc
permit-X11-forwarding
permit-agent-forwarding
Signature:
00:00:00:20:62:59:41:e3:96:ab:49:95:e8:6a:1d:a5: …
```

Add ssh signataure to step ssh inspect

---

CHANGELOG.md
command/ca/renew.go

This PR allows disabling the mTLS flow and using the token authorization flow on step ca renew. Fixes #701 
```console
$ step ca renew --force --mtls=false mariano.crt mariano.key
Your certificate has been saved in mariano.crt.
```

Force renewal with token

---

command/completion/completion.go

Hello
Fish shell auto-completion
The step CLI is already offering support for bash and zsh auto-completion, but fish was not provided yet.
To improve the user experience and improve discoverability of the tool.
```sh
step completion fish > ~/.config/fish/completions/step.fish
```
With the help of https://github.com/urfave/cli/pull/848
Thank you!

Add fish shell auto-completion

---

command/certificate/install.go

Fixes a description in `step certificate uninstall` help text
Confusing type in command description

Fix certificate uninstall description

---

CHANGELOG.md
command/certificate/create.go
command/certificate/sign.go
flags/flags.go
flags/flags_test.go

This PR allows to use user variables in the templates used in `step certificate create` and `step certificate sign`.
Fixes #719

Templates variables

---

command/ca/init.go

This PR adds the flags `--kms-root`, `--kms-intermediate`, `--kms-ssh-host` and `--kms-ssh-user` used to avoid the prompt when generating a PKI on AzureKMS.
Fixes #721

Add flags for kms keys

---

command/ca/provisioner/caConfigClient.go
internal/command/inject.go
usage/html.go

This PR ignores three new errors that appear with golangci-ling 1.49

Ignore lint errors.

---

usage/printer.go

I want to distinguish the reference docs from the rest of the documentation, and adding a `category` is a better way to do that than using the `layout` as a proxy. See smallstep/docs#131 for where this will be applied.

Add category to command reference Markdown front matter

---

.gitignore
command/ca/certificate.go
command/ca/provisioner/add.go
flags/flags.go
go.mod
go.sum
internal/cryptoutil/cryptoutil.go
utils/cautils/acme_flow.go
utils/cautils/acmeutils.go

Currently the yubikey KMS implements the attestation interface, this experimental commit uses that interface to request a certificate using ACME with the device-attest-01 challenge.

Implement device-attestations for yubikeys

---

command/ca/provisioner/add.go
command/ca/provisioner/provisioner.go
command/ca/provisioner/update.go
go.mod
go.sum

The flag `--x5c-root` in `provisioner add` and `provisioner update` should be plural, because you can configure multiple root CAs to be trusted.

--x5c-root → --x5c-roots

---

cmd/step/main.go
command/ssh/config.go
make/common.mk

* use errors.As with interface{} correctly

Fix unused linter warnings

---

command/ca/acme/eab/add.go
command/ca/acme/eab/list.go
command/ca/acme/eab/remove.go
command/ca/admin/add.go
command/ca/admin/list.go
command/ca/admin/remove.go
command/ca/admin/update.go
command/ca/policy/actions/cn.go
command/ca/policy/actions/dns.go
command/ca/policy/actions/emails.go
command/ca/policy/actions/ips.go
command/ca/policy/actions/principals.go
command/ca/policy/actions/remove.go
command/ca/policy/actions/uris.go
command/ca/policy/actions/view.go
command/ca/policy/x509/wildcards.go
command/ca/provisioner/add.go
command/ca/provisioner/remove.go
command/ca/provisioner/update.go
command/ca/provisioner/webhook/add.go
command/ca/provisioner/webhook/remove.go
command/ca/provisioner/webhook/update.go
flags/flags.go
utils/cautils/token_generator.go

On commands like "step ca provisioner add", the "--password-file" flag was used with two different purposes, to encrypt a new JWK key and to decrypt the admin JWK key. This change adds an extra flag --admin-password-file to make this different.
Fixes #744

Add --admin-password-file flag

---

command/oauth/cmd.go

It adds the header `Accept: application/json` so OAuth services like GitHub returns the data in the appropriate form instead of using `application/x-www-form-urlencoded`. It also configures GitHub as a new provider as it does not have a "well-known" URL.
The new header does not cause any issues on Google or Microsoft.
Fixes #740

Add support for OAuth using GitHub

---

CHANGELOG.md
command/ca/sign.go
command/ca/sign_test.go
go.mod

This fixes the root cause of https://github.com/smallstep/certificates/issues/1181.

Fix `mergeSans` to include the CSR URIs

---

systemd/cert-renewer@.service
systemd/ssh-cert-renewer.service

Only restart services which are actually running
A service might be enabled by default but not currently running. With the old code we would restart it in this case. is-active only touches currently running services.
systemd

Only restart services which are actually running

---

CHANGELOG.md
go.mod
go.sum

Fix CA certificates path for SLSE: https://github.com/smallstep/truststore/pull/16

Upgrade `smallstep/truststore` to fix CA certificates on SLSE

---

command/oauth/cmd.go

The OAuth2.0 spec (https://www.rfc-editor.org/rfc/rfc6749#section-5.1) dictates that there should/could be a `scope` parameter in responses from calls to the `/token` endpoint. Including this in the cli output is useful for debugging access tokens etc.
Include `scope` response param in output
Helps when debugging/validating access tokens from various OAuth providers
💔Thank you!

Add scope token response param

---

command/ca/provisioner/provisioner.go

This PR fixes an error when editing ca.json locally. `step` will try to connect to the CA, but if this is not up, it will fail instead of attempting the local edit.

Fix provisioner add when server is not online

---

command/ca/init.go

Noticed some issues running actions for https://github.com/smallstep/cli/pull/837. Some file wasn't formatted properly and resulted in the [following output](https://github.com/smallstep/cli/actions/runs/4055757550/jobs/6979640264) on GitHub Actions:
```
Running [/home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format=github-actions --timeout=30m] in [] ...
Error: File is not `goimports`-ed (goimports)
```
But no further info on what file it was about.
File might've been in the Actions cache, as I hadn't pulled latest `master` yet.

Fix `goimports` error in GitHub actions

---

cmd/step/main.go

- we still compile and test with go 1.19 so we won't remove the newly deprecated code yet.

Ignore rand.Seed deprecation.

---

go.mod
go.sum

This PR upgrades github.com/smallstep/certinfo. The new version includes a fix of the YubiKey touch policy description.

Upgrade github.com/smallstep/certinfo

---

command/oauth/cmd.go

This commit fixes a reported problem of EOF errors on device authentication flows. This fix prevents re-using the TCP connection between requests to the same host, which resolves the issue.

Prevent re-use of TCP connections on step oauth

---

docker/Dockerfile.debian

Related to smallstep/certificates#1286

Add a debian:bullseye base image

---

command/certificate/create.go
command/crypto/jwk/create.go
command/crypto/keypair.go
utils/cli.go

Before this commit, the CLI would allow specifying RSA key sizes smaller than 2048 when also setting `--insecure`, but creation of the key would still fail with `the size of the RSA key should be at least 2048 bits`, originating from the `keyutil.generateRSAKey` function.
This commit enables the insecure mode for the `keyutil` package when `--insecure` is provided, allowing short RSA keys to be created.
While there are existing tests for checking (in)compatible CLI flags that involve short RSA keys, the command didn't seem to be actually executed as part of the test. That's part of the reason why this bug wasn't found earlier, I think.

Fix error when using `--insecure` and creating RSA keys <2048 bits

---

.github/workflows/release.yml

See https://github.com/goreleaser/goreleaser/commit/d18adfb57ee951787536b22b62f2a5ebc511c716 for details

Replace deprecated GoReleaser --rm-dist flag with --clean

---

.github/workflows/release.yml

This commit adds a workflow to build a docker image using Debian bullseye. The image format will be like this:
- smallstep/step-cli:bullseye
- smallstep/step-cli:0.24.0-bullseye

Add a docker image using debian

---

command/ca/revoke.go

Should this also say "Active revocation is only supported in Certificate Manager: https://u.step.sm/cm"?

Remove 'not currently supported' from step ca revoke help text for active revocation

---

command/fileserver/fileserver.go

This commit adds the option of reloading the certificates used by the test command `step fileserver`. If the HUP signal is sent to the fileserver and is using certificates, the same file will be reloaded from the disk and used.

Add reload support for test command step fileserver

---

token/parse.go

To be complete, this feature would require a go.mod bump for github.com/smallstep/certificates once the linked PR is merged and released.
Add all knowns Azure issuers for IMDS token
When step is running on an Azure virtual machine in an Azure cloud different from "Public", the issuer is set to a different URL. This PR adds support for Public, China, Germany and US Gov clouds (waiting on a confirmation from Azure for US Gov and Germany URL)
Provides greater support for more environment.
No as there is no external configuration change needed for this feature
No as there is no external configuration change needed for this feature
https://github.com/smallstep/certificates/pull/1309

Add support for alternate issuers for Azure tokens

---

utils/cautils/token_generator.go

This commit properly detects the algorithm used for JWT signing when using ECDSA keys. The previous version always picked ES256, even if P-384 or P-521 were used.

Detect the proper algorithm when signing with x5c certs

---

CHANGELOG.md
go.mod
go.sum

This commit upgrades the version of go.step.sm/crypto with a fix for encrypting keys using PKCS#8.

Update go.step.sm/crypto with fix for PKCS#8

---

command/ca/provisioner/provisioner.go

We only had one instance of this, so instead of making a general fix for this, I just changed the text.

cli reference: next.js doesn't like {}'d values in Markdown

---

command/api/token/create.go

This PR uses the code block to avoid word-wrapping an example. It also makes the example title uppercase to match the rest of the commands:
Before this fix, the examples block looked like this:
```
Examples
$ step api token create ff98be70-7cc3-4df5-a5db-37f5d3c96e23 internal.crt
internal.key
```
With the fix it looks like this:
```
EXAMPLES
Use a certificate to get a new API token:
$ step api token create ff98be70-7cc3-4df5-a5db-37f5d3c96e23 internal.crt internal.key
```

Fix word-wrapping in step api token create example

---

command/api/token/create.go
command/api/token/token.go

--audience flag for step api token create
Allows tokens to be issued for audiences besides the API gateway
💔Thank you!

Add audience flag to api token create

---

command/certificate/create.go

Quick bug fix for the CSR signer.
Note: this builds on top of the `--ca-kms` changes.

Pass key to be signed as signer for the CSR instead of signing key

---

command/certificate/create.go
command/certificate/sign.go
go.mod
go.sum
internal/cryptoutil/cryptoutil.go

When creating a certificate for a public key backed by a KMS that doesn't allow the key to also be used for signing, or in cases where the private key isn't readily available to sign the (internally used) CSR, `--skip-csr-signature` can be passed to skip signing the (internally used) CSR.
This option is not compatible with `--csr`, because that requires a CSR with a valid signature to be produced.
Note: this builds on the changes in #945 and depends on the changes in ~~https://github.com/smallstep/crypto/pull/239 to be finalized. After merging the changes from https://github.com/smallstep/crypto/pull/239~~ https://github.com/smallstep/crypto/pull/248. 
Will add example usage when updating with the latest `smallstep/crypto`.

Add `--skip-csr-signature` option

---

command/crypto/jwk/create.go
go.mod
go.sum

This PR increases the number of PBKDF2 iterations to 600k in `step crypto jwk create` and upgrades `go.step.sm/crypto` dependency to use 600k when adding a new certificate to a ca using `step ca provisioner add`.

Increase the number of PBKDF2 iterations to 600k

---

token/parse.go
token/parse_test.go

Service account tokens issued by the Kubernetes API server in recent versions are valid OIDC tokens but do not contain an email in the payload. Update the Payload Type test to interpret tokens with [all five required claims](https://openid.net/specs/openid-connect-core-1_0.html#IDToken) as OIDC tokens even if they do not have an email claim.
An example Kubernetes OIDC token:
```json
{
"aud": [
"step-ca"
],
"exp": 1686076066,
"iat": 1686072466,
"iss": "https://kubernetes.default.svc.cluster.local",
"kubernetes.io": {
"namespace": "default",
"pod": {
"name": "pod",
"uid": "98844dbc-d248-4ddb-b385-81643892908d"
},
"serviceaccount": {
"name": "default",
"uid": "e79de63f-8842-46bc-9931-c277c4993994"
}
},
"nbf": 1686072466,
"sub": "system:serviceaccount:default:default"
}
```
Detect OIDC tokens …

Detect OIDC tokens issued by Kubernetes

---

.goreleaser.yml

https://github.com/smallstep/cli/releases/tag/v0.24.2-rc.6
I just want to note that while the filenames of the archives are different, their contents is the same. Including the directory name, which still contains the version number even if the archive name is unversioned:
x step_0.24.2-rc.6/LICENSE
x step_0.24.2-rc.6/README.md
x step_0.24.2-rc.6/autocomplete/README.md
x step_0.24.2-rc.6/autocomplete/bash_autocomplete
x step_0.24.2-rc.6/autocomplete/zsh_autocomplete
x step_0.24.2-rc.6/bin/step
This also adds more files to the assets for each release, which makes that list a little harder to look at.

Add unversioned release artifacts to build

---

command/api/token/create.go

API auth tokens with team slug
Previous you needed to supply the team UUID to get an auth token for the API.
Getting an auth token from the Gateway API.
💔Thank you!

Create API tokens with team slug

---

cmd/step/main.go
go.mod
go.sum

This commit upgrades cli-utils and crypto packages that remove the automatic initialization of the STEPPATH.
Requires:
- https://github.com/smallstep/cli-utils/pull/73
- https://github.com/smallstep/crypto/pull/298

Remove automatic initialization of the STEPPATH

---

internal/plugin/plugin.go

This PR adds support for `PATHEXT` in the `(step path)/plugins` directory, as well as support for `.ps1` execution.
Example PowerShell script in `C:\Users\herman\.step\plugins\step-script-plugin.ps1`:
```powershell
Write-Host 'Hello from PowerShell, step!'
Write-Host $args
```
```console
C:\Users\herman\Desktop>step.exe script bla foo
Hello from PowerShell, step!
bla foo
```
Currently the behavior is to fallback to some well-known executable extensions, including `.ps1`, if `PATHEXT` is not set. If `PATHEXT` is set, it is used to extract the executable extensions. By default, `PATHEXT` does not include `.ps1`, so that should be added if necessary.
Not sure if `PATHEXT` makes sense in `(step path)/plugins`. It can go both ways.

Find more plugins on Windows

---

command/crypto/jwt/verify.go

`len` returns 0 if the slice is nil. From the Go specification [^1]:
> "1. For a nil slice, the number of iterations is 0."
Therefore, an additional `len(e.Audience) != 0` check for before the loop is unnecessary.
[^1]: https://go.dev/ref/spec#For_range

crypto/jwt: remove redundant `len` check in verify

---

command/certificate/create.go
command/certificate/sign.go

As reported in https://github.com/smallstep/cli/issues/1051, the example template printed in the help has `*sa.PublicKey` instead of `*rsa.PublicKey`. This is likely due to the help text preprocessor.
This commit adds an underscore to `*_rsa.PublicKey`, which tricks the help text preprocessor into simply printing `*rsa.PublicKey`, ignoring it to be processed as Markdown.
A better fix might be to change the help text processor, but there are no tests, and it's used widely, so it's a riskier method for not too much gain.
Note that the output in the help text in the CLI is the same as on the website: https://smallstep.com/docs/step-cli/reference/certificate/create/#templates, so this PR fixes that issue too.

Fix leaf certificate `*rsa.PublicKey` example

---

utils/cautils/acmeutils.go
utils/cautils/tpm.go

This commit allows passing the device name option when initializing a TPM in the acme flow. It also allows passing the attestation-ca-url in the URI, as we can use a similar URI in `step kms` commands and `step ca certificate`.

Allow the define a custom tpm device

---

go.mod
go.sum

The new version of truststore includes the fix for installing the certificates in some linux systems.
See smallstep/truststore#24

Upgrade truststore

---

command/completion/completion.go

zsh only reads the first line of a file when searching for `#compdef` lines. The completion script added a comment above this line and caused zsh autocomplete to fail.
https://zsh.sourceforge.io/Doc/Release/Completion-System.html
bugfix for zsh completion
zsh autocompletion didn't work before
yes, already exists
anyone using zsh
n/a
https://zsh.sourceforge.io/Doc/Release/Completion-System.html
> When compinit is run, it searches all such files accessible via fpath/FPATH and reads the first line of each of them. This line should contain one of the tags described below. Files whose first line does not start with one of these tags are not considered to be part of the completion system and will not be treated specially. 
💔Thank you!

Fix command completion for zsh

---

command/crypto/jwe/decrypt.go

add: `--password-file` option for `step crypto jwe decrypt`.
The `encryptedKey` generated by `--type=jwk` in `step ca provisioner add` is in PBES2 format. This is hard-coded and difficult to change.
Therefore, in the implementation before this commit, after the key to decrypt is entered in the standard input, the executor must interactively enter the password specified when generated in the standard input. The `--key` option and others cannot be used at this time because of formatting problems. However, trying to do this programmatically is difficult, as the format of `ui.PromptPassword` is too specific for manual execution, or reading stderr output, etc., and trying to add additional standard input passwords in a programmatic and automatic way is very It was very difficult. Therefore, I …

feat: add: --password-file option for step crypto jwe decrypt

---

.github/workflows/release.yml
docker/Dockerfile.debian

I've tested that `step` builds and runs properly using the `debian:bookworm` base image and `golang:bookworm` builder image.

Docker: Update Debian build to use `debian:bookworm`

---

command/ca/init.go

This commit permits you, when using the --root and --key options, to pass
the password for decrypting the key in --key-password-file rather than
requiring an interactive prompt.
Example usage:
step ca init --root root.crt --key root.key \
--key-password-file root_key_password ...
Closes #453

Teach step ca init about --key-password-file

---

go.mod
go.sum

Addresses https://github.com/smallstep/certificates/issues/1745. An error occurring due to a corrupted CLI configuration should now result in the error being returned. The fix is in https://github.com/smallstep/cli-utils/pull/109.

Fix ignored error from loading vintage context configuration

---

command/ssh/needsRenewal.go

Allow stdin input of cert for needs-renewal
This allows users who have ephemeral certs (certs only in agents) to use needs-renewal without writing the cert to disk. This functionality already exists for inspect; I merely ported it over.

Allow stdin input of cert for needs-renewal

---

command/ssh/certificate.go
command/ssh/login.go

Add --kty, --curve, and --size to ssh commands (login, certificate)
Allow users flexibility to control their SSH key configuration
implements feature request from https://github.com/smallstep/cli/issues/477

Add support for setting ssh key types

---

command/certificate/verify.go
command/crl/inspect.go
internal/crlutil/crl_extensions.go
internal/crlutil/crlutil.go
internal/crlutil/signature_algorithms.go

Add OCSP and CRL support to certificate verify
Add args and functionality to certificate verify to check a CRL and OCSP for a certificate based on the extensions. Users can pass flags to enable verification of each (CRL, OCSP). The command will try and get the CRL and OCSP server from the certificate extensions if the endpoints are not provided.
Implements #845
- I tested the logic against a valid certificate, invalid OCSP/CRL endpoints, and a revoked certificate
- I moved some of the functions and structs from crl into its own internal package `internal/crlutil` so it can be reused
- Long term if [this](https://github.com/golang/go/issues/40017) ever is adressed then a lot of this can be removed in favor of using built in functionality in crypto/x509

Add OCSP and CRL support to certificate verify

---

command/certificate/verify.go
command/crl/inspect.go

This commit fixes the linter errors introduced in merged PRs,

Fix linter errors

---

internal/cryptoutil/cryptoutil.go

This commit fixes a typo in the JOSE algorithm specified for Ed25519 keys when a kms is used.
Fixes #1207

Set proper JOSE algorithm for Ed25519 keys

---

.goreleaser.yml

This is just to fix a deprecation warning for goreleaser v2—the version which we are already running.
https://goreleaser.com/blog/goreleaser-v2/#upgrading

Update goreleaser YML version

---

command/certificate/inspect.go

This commit fixes the error message displayed when we run `step certificate inspect --short --format pem ...`.

Fix error message on step certificate inspect

---

Makefile

Fixes #1211. See issue for motivation.

Makefile: fix usage of install command line flags on macOS

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
scripts/package-repo-import.sh
scripts/package-upload.sh

This adds support for signing RPM and Deb packages and uploading them to GCP Artifact Registry. It also changes the RPM and Deb file name format to use the ConventionalFileName macro in GoReleaser.

Add support in for signing and publishing RPM and Deb packages to GCP Artifact Registry

---

.github/workflows/release.yml
.goreleaser.yml
scripts/package-repo-import.sh

This PR moves the package upload logic so the packages always upload to the GCS bucket but they will not import into the YUM and Apt repos if it is a prerelease.

Prerelease fixes

---

utils/sysutils/sysutils_windows.go

I have tested this build with PowerShell 5.1 and PowerShell 7.4 in Windows 11
I have not tested in Windows 10 pre- and post- anniversary edition

Fix PowerShell 5.1 CLI crashes in Windows 11

---

.github/workflows/release.yml
.goreleaser.yml

This PR fixes the links in the releases.

Fix Release URLs with new file name formats.

---

internal/crlutil/crlutil.go

Not sure if this was an oversight, or done on purpose, but extensions in RevocationListEntries were not being parsed. Now they get parsed.
Before change:
```
❯ step crl inspect --insecure 'http://crl4.digicert.com/sha2-ev-server-g1.crl' | grep "Revoked Certificates:" -A 5
Revoked Certificates:
Serial Number: 2799225036922445944820450433099856353 (0x021B1C73250B47C4CE8F305E639B79E1)
Revocation Date: 2023-08-23 10:43:00 +0000 UTC
Serial Number: 14874532436251617487517665762619838282 (0x0B30BB11F55A7DF580DDC276AF324F4A)
Revocation Date: 2023-11-23 12:19:17 +0000 UTC
Serial Number: 21201432819745242598424189347483327802 (0x0FF33F57C756BC0BA8A6B78606179D3A)
```
After change:
```
❯ ./bin/step crl inspect --insecure 'http://crl4.digicert.com/sha2-ev-server-g1.crl' | grep "Revoked Certificates:" …
```

Parse crlEntryExtensions in CRLs

---

scripts/package-upload.sh

This PR skips uploading the armhf6 deb to our APT repo due to arch conflicts with armhf.

Skip uploading armhf6 deb

---

docker/Dockerfile.debian

Fix Debian dockerfile

---

exec/exec.go

support for OpenInBrowser on Android
without this patch, doing "step ssh login" with and OIDC-provider results in:
> Cannot open a web browser on your platform.
> 
> Open a local web browser and visit:
> http://....
> 
with this patch applied, the browser is opened automatically
(behind the scenes by using xdg-open)
I tested this on "termux" on Android (which ships step-cli as one of its termux-packages). 
(On termux, "xdg-open" links to "termux-open", which then calls Android's "am" (Activity Manager))
💔Thank you!

OpenInBrowser on Android as well

---

command/ca/certificate.go

The `step ca certificate` command doesn't have a `--bundle` switch, and yet the usage text suggests it is available.
This PR fixes that. I think this got reintroduced accidentally, see #521 .

Remove `--bundle` from `step ca certificate` usage text

---

Makefile
utils/cautils/bootstrap.go

This commit sets the proper redirect-url parameter in the defaults.json if the flag `--redirect-url` is given in the bootstrap command.

Handle the redirect-url flag

---

internal/cast/cast_test.go

Fixes #1367.
In the absence of `arm32` runners in our CI, I've tested this locally with a Dockerfile roughly equivalent to this (based on the `cli` Dockerfile):
```dockerfile
FROM --platform=linux/arm golang:alpine AS builder
WORKDIR /src
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN apk add --no-cache make git curl
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT
RUN --mount=type=cache,target=/root/.cache/go-build \
--mount=type=cache,target=/go/pkg \
GOOS="${TARGETOS}"; \
GOARCH="${TARGETARCH}"; \
if [ "${TARGETARCH}" = "arm" ] && [ "${TARGETVARIANT}" ]; then \
GOARM="${TARGETVARIANT#v}"; \
fi; \
CGO_ENABLED=0 GOOS_OVERRIDE="GOOS=${GOOS} GOARCH=${GOARCH} GOARM=${GOARM}" \
go test -timeout 30s github.com/smallstep/cli/internal/cast 
RUN …
```

Fix `cast` package tests for `linux/arm32`

---

command/oauth/cmd.go

This PR adds support for `STEP_OPEN_BROWSER` env var which if set to  `STEP_OPEN_BROWSER=false` it will skip opening the default browser and just output the authURL to stderr.

Skip opening the default browser if STEP_OPEN_BROWSER=false

---

command/ca/token.go
token/options.go
token/token.go
utils/cautils/certificate_flow.go
utils/cautils/token_generator.go

Add the `--set` and `--set-file` flags to the `step ca token` command, allowing the user to set keys in the "user" claim in the resulting JWT.
Custom user data in tokens
Lack of ability to pass custom _trusted_ data to a template without a pre-existing CSR.
Yes, in the CLI help for `step ca token`.
Online JWT token flow
Offline token flow, because `cautils.OfflineTokenFlow` doesn't support `tokenOpts`. Enforced by flags validation.

command/ca/token: support custom "user" claim

---

command/ca/token.go

The unescaped curly braces result in a broken docs site. Besides that, other template variables are also not demarcated using curly braces.

Change `.Token.user.field` to not use curly braces

---

.goreleaser.yml
Makefile
README.md
docs/CONTRIBUTING.md
docs/local-development.md
utils/cautils/token_flow_test.go

The `goreleaser` target has been adapted to allow for building CLI 
releases that are very similar to the ones that we release as part of 
our GitHub Actions release process. The target skips the hooks that 
trigger binaries to be pushed to GCP, allowing the release process to 
happen locally.
This PR also allows the GoReleaser process to be performed with
either its Pro or OSS version using a single config file.
Other changes in this PR:
- Updated documentation for contributing to the `step` codebase
- Replaced list of enabled linters with the current `golangci-lint` config
- Enabled git data to be embedded into binary
- Fixed some GoReleaser config deprecations
- Fixed the GoReleaser Pro download URL for AMD64 
- Fixed some test cases that failed when ran using `make test`
Example build …

Improve local GoReleaser build process and development docs

---

.goreleaser.yml

By using `envOrDefault` an issue is prevented in evaluating the template before a release is created. By setting the default value to `ENV_VAR_GPG_PRIVATE_KEY_FILE_NOT_SET`, this value is then shown in the error message at signing time.
The reason for changing this is so that it becomes possible to create local, unsigned (Linux package) releases when creating a release as follows:
`goreleaser release --snapshot --clean --skip sign,after`
Before the change (see #1404):
```console
...
• linux packages
⨯ release failed after 6m39s               error=template: failed to apply "{{ .Env.GPG_PRIVATE_KEY_FILE }}": map has no entry for key "GPG_PRIVATE_KEY_FILE"
```
After (skipping `sign`):
```console
...
• linux packages
• creating                                       package=step-cli …
```

Use `envOrDefault` for `GPG_PRIVATE_KEY_FILE` environment variable

---

command/ca/token.go

Fixes [smallstep/docs#1065](https://github.com/smallstep/cli/issues/1065)

Fix step ca token help text around validity period flags

---

internal/sshutil/agent_windows.go

Add environment variable `SSH_AUTH_SOCK` support to Windows environments.
This feature will allow Windows ssh agents which run entirely within the Windows environment (like PuTTY) to work with step cli. It will allow the agents to use Named Pipes other than the default OpenSSH Agent specific pipe (`\\.\\pipe\\openssh-ssh-agent`).
`SSH_AUTH_SOCK` is an environment variable specifying how clients can connect and interact with an SSH agent (https://datatracker.ietf.org/doc/html/draft-ietf-sshm-ssh-agent). If it exists, clients like step cli should load ssh keys into the agent it points to. At present, it is not wholeheartedly respected on Windows systems.
The existing code (in `internal/sshutil/agent_windows.go`) only includes logic to handle the existence of `SSH_AUTH_SOCK` in Unix-like …

Add SSH_AUTH_SOCK support to Windows environments.

---

cmd/step/main.go
go.mod
go.sum
integration/shared_test.go
internal/cmd/root.go

See https://github.com/rogpeppe/go-internal/pull/281.
Replaces https://github.com/smallstep/cli/pull/1444.

Fix testscript `RunMain` deprecation
