command/certificate/inspect.go
command/certificate/verify.go

add --bundle option to certificate inspect

---

.gitignore
.travis.yml
CHANGELOG.md
Makefile
README.md
distribution.md

* update distribution documentation
* fix #14
💔Thank you!

add travis artifact upload on successful tagged build

---

crypto/pki/pki.go

Output defaults.json when initializing PKI and printing CA configuration.

Add print defaults.json on CA init

---

cmd/step/main.go
command/ca/certificate.go
command/ca/renew.go

Add support for a renew daemon that will renew periodically a certificate.

Renew daemon

---

command/ca/init.go
crypto/pki/pki.go
ui/options.go
ui/ui.go

Add flags to specify the arguments to `step ca init` to make it non-interactive.

Add flags to specify the arguments to `step ca init`

---

Gopkg.lock
Gopkg.toml
cmd/step/main.go
command/ca/certificate.go
command/ca/offline.go
command/ca/provisioner/add.go
command/ca/provisioner/remove.go
command/ca/token.go
command/oauth/cmd.go
crypto/keys/key.go
crypto/pki/pki.go
exec/exec.go
jose/types.go

This PR makes the CLI compatible with the provisioner refactoring in certificates and adds support for OIDC tokens in the ca commands.

OIDC support on the CLI

---

command/ca/certificate.go
command/ca/offline.go
command/ca/token.go

This PR adds OIDC support with the offline mode
Fixes #99

Add oidc support to offline mode.

---

command/ca/revoke.go

Please describe your pull request.
💔Thank you!

revoke: Verify # of command line args

---

cmd/step/main.go
command/fileserver/fileserver.go

This PR adds a new hidden command `step fileserver`. 
This command starts a file server on a given directory, it supports HTTP and HTTPS with a given certificate file.

Add test command step fileserver

---

Gopkg.lock
Gopkg.toml
command/ca/ca.go
command/ca/certificate.go
command/ca/offline.go
command/ca/token.go

Add subject to the list of SANs in cloud providers if disableCustomSANs is set to false.
This PR also includes a fix in zcrypto to support new provisioners https://github.com/smallstep/zcrypto/commit/0eaa490bf930eb2c8f1fd0dec8750619588aadae

Add subject to the list of SANs in cloud providers

---

command/oauth/cmd.go

Not every identity provider allows a dynamic port number in the allowed callback URL. So this helps to configure static port number for the callback listener. 
`step oauth --listen 127.0.0.1:8080 ...`
💔Thank you!

Added configurable callback listener

---

command/certificate/create.go
crypto/x509util/leafProfile.go

Add a self-signed x509 profile and enable created from cli

---

command/certificate/create.go
command/certificate/sign.go

Add bundle option to 'certificate [sign|create]'

---

usage/html.go

Misunderstood the requirements for underscores in `index.md` file names. Only `_index.md` for directories that have no sub-directories.

Minor fix: Hugo wants underscores in dirs with subdirs only

---

Gopkg.lock
command/ca/certificate.go
command/ca/sign.go
command/certificate/create.go
crypto/x509util/crt.go
crypto/x509util/crt_test.go
crypto/x509util/profile.go

Add emails sans to `ca [sign|certificate]` and `certificate create`

---

command/ca/init.go
crypto/pki/pki.go
usage/usage.go

* step
* step help
* step ca init
* Fixes #170

Solicit feedback from users

---

command/crypto/change-pass.go

Add ability to set no password when using change-pass

---

Gopkg.lock
command/ca/bootstrap.go
command/ca/ca.go
command/ca/certificate.go
command/ca/federation.go
command/ca/health.go
command/ca/renew.go
command/ca/revoke.go
command/ca/root.go
command/ca/sign.go
command/ca/token.go
command/ssh/certificate.go
crypto/pki/pki.go

* Use global flags rather than flags local to the CA package.
* Alphabetize flag names so they're easier to parse for humans.
* Fix some documentation snafus.
* crt -> cert where possible. At least for internal naming. Not gonna
change JSON req/resp bodies b/c that would affect clients.
Please describe your pull request.
💔Thank you!

Changes based on SSH CA PR Review

---

command/ca/provisioner/add.go
crypto/pki/pki.go

Enable SSH by default if `step ca init --ssh` is  used.
Fixes #149

Enable SSH

---

command/ca/certificate.go

Allow decrypting the provisioner from the 'ca certificate' command.

---

command/crypto/jws/sign.go

Add pwd-file cmd line flag to jws sign

---

command/ssh/certificate.go

* only when there are no explicit principals requested.

ssh certificate nil principals for OIDC

---

cmd/step/main.go
command/ssh/checkHost.go
command/ssh/ssh.go
errs/errs.go
go.mod
go.sum

Add a few graceful errors to checkHost

---

command/crypto/key/key.go
command/crypto/key/public.go

This PR adds the command `step crypto key public` that prints or writes the public key corresponding to a private key.

Add command to print a public key

---

command/ssh/login.go
flags/flags.go

This PR fixes `--provisioner-password-file` flag in `step ssh login`

Fix --provisioner-password-file flag in step ssh login

---

command/ca/renew.go

Log the common name of the certificate renewed by the renewDaemon

---

docs/CONTRIBUTING.md

To link to Gitter instead of email/twitter.

Update CONTRIBUTING.md 

---

command/crypto/crypto.go

Fix typo in crypto description
💔Thank you!

Fix typo in crypto description

---

command/crypto/key/inspect.go
command/crypto/key/key.go

This PR adds new command `step crypto key inspect` has been added to inspect
keys in pem, ssh or der format.

Add command to inspect keys.

---

command/ca/bootstrap.go
command/ssh/config.go
flags/flags.go

Improve the `step ca bootstrap` command to fully support the `--team` flag.

Improve ca bootstrap with team flag

---

command/certificate/fingerprint.go
command/certificate/inspect.go
command/certificate/lint.go
command/certificate/remote.go
command/certificate/remote_test.go
command/certificate/verify.go
flags/flags.go

Add ServerName indication flag to remote certificate fetching commands.

---

command/ca/provisioner/add.go
command/ca/provisioner/remove.go

Output information about restarting the CA after provisioner add|remove

---

command/ca/renew.go

Enable key decryption in `ca renew`

---

command/ca/ca.go
command/ca/certificate.go
command/ca/token.go
command/ssh/ssh.go

Don't reuse san and principal flags to avoid confusing usage.

---

command/crypto/otp/verify.go

Fix flag interpretation and usage in `otp verify`

---

crypto/x509util/profile.go
crypto/x509util/profile_test.go

Remove standard Extensions from ExtraExtensions before CreateCert

---

command/ca/token.go

Should be self-explanatory 😄 
Hopefully I will follow up with a more substantial contribution than one character

s/--sans/--san in token CLI docs

---

make/docker.mk

Add docker build for arm64

---

README.md
command/ca/bootstrap.go
command/crypto/jwt/verify.go
flags/flags.go
utils/cautils/teams.go

This PR is mostly about refreshing the README.
After talking with @alanchrt about it this morning, I also changed references to "team name" to "team ID" — which I will make consistent in the quickstarts & docs too.
Team name: `Example Co`
Team ID: `exampleco`

README updates, and "team name" -> "team ID"

---

command/ca/bootstrap.go
command/ca/federation.go
command/ca/health.go
command/ca/provisioner/getEncryptedKey.go
command/ca/provisioner/list.go
command/ca/renew.go
command/ca/revoke.go
command/ca/root.go
command/ca/token.go
errs/errs.go
flags/flags.go
flags/flags_test.go
utils/cautils/acmeutils.go
utils/cautils/certificate_flow.go
utils/cautils/client.go
utils/cautils/token_flow.go

Implicitly require https scheme for ca-url cmd line arg

---

Makefile
make/bundle.sh

add .zip archive option for bundling step

---

README.md

macOS is the canonical name for Apple's current desktop operating system (and has been for a very long time). It's also the term used on the brew page that's linked from this section.

brand: macOS

---

.travis.yml
make/docker.mk

This is just an update to `make/docker.mk` and `.travis.yml` based on lessons learned from smallstep/certificates#353

Parallel of smallstep/certificates#353

---

command/ca/bootstrap.go

Fix ca bootstrap --team (don't require caURL)

---

command/ca/revoke.go

Allow for encrypted key file in `step ca revoke`

---

command/certificate/p12.go

This PR adds minor edits in the docs for the `step certificate p12` command.

Add minor edits for `step certificate p12` docs.

---

command/certificate/create.go
command/certificate/sign.go

Add password flags to certificate create & sign

---

command/ca/sign.go
utils/cautils/certificate_flow.go

Certs requests using K8sSA tokens should not use k8ssa sub

---

README.md

Please provide a working example of a command that can be used on Arch Linux to install step.
Thank you!

Arch Linux installation

---

command/certificate/create.go

Fix duration flags incompatible with csr

---

command/ca/renew.go

Add --pid-file flag to step ca renew

---

command/crypto/change-pass.go
jose/encrypt.go

- allow the command to be completely non-interactive
fixes #416

Add --password-file and --new-password-file flags to change-pass

---

command/oauth/cmd.go

Close https://github.com/smallstep/cli/issues/215

OAUTH: add --prompt option for Authentication Request

---

command/crypto/change-pass.go

See https://github.com/smallstep/cli/pull/417/files#diff-52d7170ad3b84392b1aae6a3dbf7317981f3c41baf87dae03b47e5a81d0a5d07R76

Fix flag usage typo introduced by #417

---

command/ca/federation.go
command/ca/root.go

This change allows to print the root or federated roots instead of
downloading to a given file. The commands affected are:
* step ca root
* step ca roots
* step ca federation

Do not require output file in `step ca root` and related commands.

---

exec/exec.go

Fix WSL2 exec detection

---

command/ssh/checkHost.go

Add --verbose option to step ssh check-host

---

.goreleaser.yml

Add arm6 to goreleaser

---

.github/workflows/release.yml
powershell/install-step.ps1
powershell/uninstall-step.ps1

@dopey what do you think of this magic

Dynamically determine version number of latest GitHub release in PowerShell installer

---

command/certificate/create.go
command/crypto/change-pass.go
command/crypto/keypair.go

Reverse insecure and --no-password in RequireWithFlag

---

make/common.mk

Implement condition to generate a release that can be run through delve.

option to build for use with delve

---

README.md

Updating gitter link to discord link
💔Thank you!

chore: update gitter to discord

---

command/crypto/key/public.go

fixes issue #470 - now can check the public key from a certificate or a key, flag function works with it as well.
ex:
step crypto key public foo.crt
step crypto key public --out foo.pem foo.crt

add functionality to check a certificates public key

---

docker/Dockerfile

Add tzdata to the docker container

---

.github/ISSUE_TEMPLATE/config.yml

update new issue template

---

.github/workflows/labeler.yml

- https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

Fix pull request labeler permissions

---

command/certificate/format.go

This PR adds support of CSRs in `step certificate format`.

Add support to format CSRs to DER and back to PEM.

---

CHANGELOG.md
command/ca/renew.go
command/ca/revoke.go
command/ca/token.go
utils/cautils/certificate_flow.go
utils/cautils/client.go
utils/cautils/offline.go
utils/cautils/token_flow.go
utils/cautils/token_generator.go

Thread CA password decryption into offline CA bootstrap

---

utils/cautils/acmeutils.go

If --root is given as a parameter, not-after/not-before is allowed.
If not, then treat it as any public CA.
This does not change any functionality, but rather allow skipping --root
if the private CA is already in the systems trust.
Signed-off-by: Josef Johansson <josef@oderland.se>
resolves #564 
💔Thank you!

feat: utils/cautils/acmeutils.go: Treat all public CAs the same

---

command/ca/provisionerbeta/add.go
command/ca/provisionerbeta/provisioner.go
command/ca/provisionerbeta/update.go
go.mod
go.sum

This PR adds support for adding and updating SCEP provisioners.
It also includes some small typo fixes.

Add SCEP (beta) provisioner support

---

CHANGELOG.md
command/ssh/certificate.go

Add --no-agent flag to 'ssh certificate' command

---

CHANGELOG.md
command/ssh/login.go
command/ssh/logout.go
command/ssh/proxycommand.go
command/ssh/ssh.go
crypto/sshutil/agent.go
utils/cautils/certificate_flow.go
utils/cautils/token_flow.go

This PR makes the command `step ssh login` and `step ssh logout` more intuitive. Allowing the use of them without any positional argument.

Improvements step ssh login and logout

---

flags/flags.go
integration/certificate_sign_test.go
integration/certificate_verify_test.go
integration/help_quality_test.go
integration/integration_test.go
integration/jwk_test.go
integration/jwt_test.go
integration/keypair_test.go
integration/otp_test.go

Finish the flag ParseCaURL ignore if `--offline`.

---

CHANGELOG.md

This PR adds the entries of PR #642 in the changelog

Changelog for PR #642

---

command/certificate/inspect.go
command/certificate/remote.go
command/certificate/remote_test.go

Add other url formats with default port has requested in https://github.com/smallstep/cli/issues/459

Add other url formats for certificate inspect

---

command/ssh/inspect.go

SSH certificates are marshaled to disk with the format `type base64-certificate comment`, but we only send through the wire the certificate itself, currently we need to prepend a type (or any fake string) to be able to inspect the certificate itself. This PR solves this and attempts to decode the base64-certificate if the previous method failed.

Allow to inspect ssh certificates without the type

---

CHANGELOG.md
command/ca/revoke.go

revoke <serial> must be base 10 or indicate appropriate base

---

.github/workflows/code-scan-cron.yml

[action] Add name to code-scan-cron

---

.github/workflows/ci.yml
.github/workflows/code-scan-cron.yml
.github/workflows/release.yml
.github/workflows/triage.yml

CI in forks w/ restrictive default permissions
#769
💔Thank you!

Improve Ci in forks

---

systemd/README.md

This is a copy of one of your PRs @tashian, but with signed commit and updated CI.
@tashian if this looks good to you, go ahead and merge.

Update renewal link in systemd docs.

---

go.mod
go.sum

Upgrade crypto to add support for https://github.com/smallstep/cli/pull/783

Upgrade go.step.sm/crypto

---

command/oauth/cmd.go

This PR removes the condition put in place to use Google OOB.
Fixes #675

Remove condition to use Google OOB

---

CHANGELOG.md

This PR adds missing changes in the changelog and prepares it for the v0.23.0 release.

Prepare changelog for v0.23.0 release

---

command/ca/renew.go

This will close https://github.com/smallstep/docs/issues/155

Update renew docs to clarify when mTLS is and is not used for renewal

---

CHANGELOG.md
go.mod
go.sum

This PR prepares the changelog for v0.23.1

Prepare changelog for v0.23.1

---

go.mod
go.sum

This PR upgrades the dependency in smallstep/certificates.

Upgrade version of smallstep/certificates

---

CHANGELOG.md

This PR updates the changelog for v0.23.3 release.

Add changelog for v0.23.3

---

.goreleaser.yml

Try adding arm64 goarch for nfpm build

---

CHANGELOG.md

This commit adds the changelog entries for the v0.24.0 release.

Prepare changelog for v0.24.0 release

---

docker/Dockerfile.debian

See https://github.com/smallstep/cli/actions/runs/4683638890 for a workflow run of this with an RC build

Cross-compile the Docker debian build

---

docker/Dockerfile.debian

https://github.com/smallstep/cli/actions/runs/5260780923

Assume yes on apt upgrade to avoid non-interactive prompting

---

internal/plugin/plugin.go

This PR adds support for locating Windows plugins with executable extensions. The logic is somewhat similar to what's in `exec.LookPath`, but only for the `$(step path)/plugins` directory.

Look for Windows plugins with executable extensions in plugins

---

.goreleaser.yml

Fix cosign identity regexp

---

.github/workflows/release.yml

([Here is the original commit](https://github.com/smallstep/cli/commit/85eb21a8d) that broke this file)

Fix a yaml error in release.yml that I introduced

---

go.mod
go.sum

Upgrade certinfo

---

command/ca/revoke.go

N/A
N/A
it's not important, just cosmetic
N/A
N/A
N/A
N/A
💔Thank you!

Fix typo: missing dash for --offline in help

---

Makefile

Makefile: install to /usr/local/bin, not /usr/bin

---

.github/workflows/release.yml

See https://github.com/jqlang/jq/pull/2768.

Replace `jq` `--argfile` with `--slurpfile`
